# Generated by Django 4.1.7 on 2023-05-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_product_available_for_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
