# Generated by Django 4.1.7 on 2023-05-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_product_full_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact_email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='contact_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('UPI', 'UPI')], default='Cash On Delivery', max_length=20),
        ),
    ]
