# Generated by Django 4.1.7 on 2023-05-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0008_product_contact_email_product_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=200)),
                ('secondary_number', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('current_designation', models.CharField(max_length=200)),
                ('monthly_salary', models.CharField(max_length=200)),
                ('address_of_residence', models.CharField(max_length=200)),
                ('landlord_name', models.CharField(max_length=200)),
                ('duration_lived_in_this_residence', models.CharField(max_length=200)),
                ('explanation', models.CharField(max_length=200)),
            ],
        ),
    ]
