# Generated by Django 4.1.7 on 2023-05-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='explanations',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='lease',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
