# Generated by Django 4.1.7 on 2023-05-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_remove_lease_explanations'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='required_lease_time',
            field=models.CharField(default='', max_length=200),
        ),
    ]
